version: '3'
services: 
  web: 
    build:
      context: './dev/php-${PHP_VERSION}'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        WWWUSER: '${WWWUSER}'
    user: '${WWWUSER:-1000}:${WWWGROUP:-1000}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports: 
      - '${APP_PORT:-80}:80'
    volumes:
      - './src:/var/www/html'
      - './dev/php-${PHP_VERSION}/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    networks: 
      - devmachine
    depends_on:
      - mysql
  mysql: 
    image: 'mysql/mysql-server:${MYSQL_VERSION:-latest}'
    container_name: mysql
    ports: 
      - '${MYSQL_DB_PORT:-3306}:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
      - 'devmachine-mysql:/var/lib/mysql'
    networks: 
      - devmachine
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - '${PMA_PORT:-8080}:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: '${DB_USER}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    networks: 
      - devmachine

networks:
  devmachine:
    driver: bridge
volumes: 
  devmachine-mysql:
    driver: local